import { WorkspaceData } from './types'

const now = new Date().toISOString()

export const DEFAULT_DATA: WorkspaceData = {
  rootPageIds: ['getting-started', 'team-manual', 'project-tracker', 'meeting-notes'],
  pages: {
    'getting-started': {
      id: 'getting-started',
      title: 'Statfordegree Hub 시작하기',
      icon: '🚀',
      parentId: null,
      childIds: [],
      isExpanded: false,
      createdAt: now,
      updatedAt: now,
      pinned: true,
      content: [
        {
          id: 'b1',
          type: 'heading1',
          content: 'Statfordegree Hub에 오신 것을 환영합니다',
        },
        {
          id: 'b2',
          type: 'callout',
          content: '이 워크스페이스는 팀의 업무 관리와 메뉴얼 정리를 위한 지식관리 시스템입니다.',
        },
        {
          id: 'b3',
          type: 'heading2',
          content: '주요 기능',
        },
        {
          id: 'b4',
          type: 'bullet',
          content: '📄 페이지 — 계층형 문서 작성 및 관리',
        },
        {
          id: 'b5',
          type: 'bullet',
          content: '✅ 태스크 보드 — 칸반 방식의 업무 관리',
        },
        {
          id: 'b6',
          type: 'bullet',
          content: '🔍 빠른 검색 — Cmd+K 로 어디서든 검색',
        },
        {
          id: 'b7',
          type: 'bullet',
          content: '📌 대시보드 — 최근 문서 및 진행중인 태스크 한눈에 보기',
        },
        {
          id: 'b8',
          type: 'heading2',
          content: '빠른 시작',
        },
        {
          id: 'b9',
          type: 'todo',
          content: '왼쪽 사이드바에서 새 페이지 만들어보기',
          checked: false,
        },
        {
          id: 'b10',
          type: 'todo',
          content: '태스크 보드에서 첫 번째 업무 등록하기',
          checked: false,
        },
        {
          id: 'b11',
          type: 'todo',
          content: '팀 매뉴얼 페이지에 프로세스 문서화하기',
          checked: false,
        },
        {
          id: 'b12',
          type: 'divider',
          content: '',
        },
        {
          id: 'b13',
          type: 'paragraph',
          content: '문서를 클릭하면 편집 모드가 활성화됩니다. Enter로 새 블록을 추가하고, / 입력으로 블록 타입을 변경할 수 있습니다.',
        },
      ],
    },
    'team-manual': {
      id: 'team-manual',
      title: '팀 매뉴얼',
      icon: '📚',
      parentId: null,
      childIds: ['onboarding', 'workflows'],
      isExpanded: true,
      createdAt: now,
      updatedAt: now,
      pinned: false,
      content: [
        {
          id: 'tm1',
          type: 'heading1',
          content: '팀 매뉴얼',
        },
        {
          id: 'tm2',
          type: 'paragraph',
          content: '우리 팀의 업무 방식, 프로세스, 가이드라인을 정리한 공간입니다.',
        },
        {
          id: 'tm3',
          type: 'heading2',
          content: '목차',
        },
        {
          id: 'tm4',
          type: 'bullet',
          content: '온보딩 가이드',
        },
        {
          id: 'tm5',
          type: 'bullet',
          content: '업무 프로세스 & 워크플로우',
        },
        {
          id: 'tm6',
          type: 'bullet',
          content: '커뮤니케이션 규칙',
        },
        {
          id: 'tm7',
          type: 'heading2',
          content: '커뮤니케이션 규칙',
        },
        {
          id: 'tm8',
          type: 'bullet',
          content: '슬랙 응답은 근무 시간 내 1시간 이내',
        },
        {
          id: 'tm9',
          type: 'bullet',
          content: '중요한 결정사항은 반드시 이 Hub에 문서화',
        },
        {
          id: 'tm10',
          type: 'bullet',
          content: '주간 회의는 매주 월요일 오전 10시',
        },
      ],
    },
    'onboarding': {
      id: 'onboarding',
      title: '온보딩 가이드',
      icon: '👋',
      parentId: 'team-manual',
      childIds: [],
      isExpanded: false,
      createdAt: now,
      updatedAt: now,
      content: [
        {
          id: 'ob1',
          type: 'heading1',
          content: '온보딩 가이드',
        },
        {
          id: 'ob2',
          type: 'callout',
          content: '새로운 팀원을 위한 환영 가이드입니다. 차근차근 읽어보세요!',
        },
        {
          id: 'ob3',
          type: 'heading2',
          content: '1주차: 환경 설정',
        },
        {
          id: 'ob4',
          type: 'todo',
          content: 'GitHub 계정 생성 및 팀 조직에 초대받기',
          checked: true,
        },
        {
          id: 'ob5',
          type: 'todo',
          content: 'Slack 워크스페이스 참여',
          checked: true,
        },
        {
          id: 'ob6',
          type: 'todo',
          content: '개발 환경 세팅 (README.md 참고)',
          checked: false,
        },
        {
          id: 'ob7',
          type: 'todo',
          content: '팀 매뉴얼 전체 읽기',
          checked: false,
        },
        {
          id: 'ob8',
          type: 'heading2',
          content: '2주차: 업무 파악',
        },
        {
          id: 'ob9',
          type: 'todo',
          content: '현재 진행중인 프로젝트 파악',
          checked: false,
        },
        {
          id: 'ob10',
          type: 'todo',
          content: '첫 번째 태스크 받아서 진행하기',
          checked: false,
        },
      ],
    },
    'workflows': {
      id: 'workflows',
      title: '업무 프로세스',
      icon: '⚙️',
      parentId: 'team-manual',
      childIds: [],
      isExpanded: false,
      createdAt: now,
      updatedAt: now,
      content: [
        {
          id: 'wf1',
          type: 'heading1',
          content: '업무 프로세스 & 워크플로우',
        },
        {
          id: 'wf2',
          type: 'heading2',
          content: '개발 프로세스',
        },
        {
          id: 'wf3',
          type: 'numbered',
          content: '태스크 보드에서 작업 항목 확인',
        },
        {
          id: 'wf4',
          type: 'numbered',
          content: 'feature 브랜치 생성 (feat/기능명)',
        },
        {
          id: 'wf5',
          type: 'numbered',
          content: '작업 완료 후 PR 생성',
        },
        {
          id: 'wf6',
          type: 'numbered',
          content: '코드 리뷰 요청 (최소 1명)',
        },
        {
          id: 'wf7',
          type: 'numbered',
          content: '리뷰 승인 후 main 브랜치 머지',
        },
        {
          id: 'wf8',
          type: 'heading2',
          content: '코드 리뷰 가이드라인',
        },
        {
          id: 'wf9',
          type: 'bullet',
          content: '48시간 이내 리뷰 완료',
        },
        {
          id: 'wf10',
          type: 'bullet',
          content: '건설적인 피드백 위주로 작성',
        },
        {
          id: 'wf11',
          type: 'bullet',
          content: '중요도에 따라 nit:, must:, suggest: 접두사 사용',
        },
      ],
    },
    'project-tracker': {
      id: 'project-tracker',
      title: '프로젝트 트래커',
      icon: '📊',
      parentId: null,
      childIds: [],
      isExpanded: false,
      createdAt: now,
      updatedAt: now,
      content: [
        {
          id: 'pt1',
          type: 'heading1',
          content: '프로젝트 트래커',
        },
        {
          id: 'pt2',
          type: 'paragraph',
          content: '진행중인 프로젝트 현황을 정리합니다. 자세한 태스크는 태스크 보드에서 관리하세요.',
        },
        {
          id: 'pt3',
          type: 'heading2',
          content: '현재 진행중',
        },
        {
          id: 'pt4',
          type: 'bullet',
          content: '🟢 Statfordegree Hub 구축 — 진행중',
        },
        {
          id: 'pt5',
          type: 'bullet',
          content: '🟡 API 서버 개발 — 계획중',
        },
        {
          id: 'pt6',
          type: 'bullet',
          content: '🔵 디자인 시스템 정립 — 검토중',
        },
        {
          id: 'pt7',
          type: 'heading2',
          content: '완료됨',
        },
        {
          id: 'pt8',
          type: 'bullet',
          content: '✅ 요구사항 정의 완료',
        },
        {
          id: 'pt9',
          type: 'bullet',
          content: '✅ 기술 스택 결정',
        },
      ],
    },
    'meeting-notes': {
      id: 'meeting-notes',
      title: '회의록',
      icon: '📝',
      parentId: null,
      childIds: [],
      isExpanded: false,
      createdAt: now,
      updatedAt: now,
      content: [
        {
          id: 'mn1',
          type: 'heading1',
          content: '회의록',
        },
        {
          id: 'mn2',
          type: 'paragraph',
          content: '팀 회의 내용을 정리하는 공간입니다.',
        },
        {
          id: 'mn3',
          type: 'heading2',
          content: '2025-03-06 주간 회의',
        },
        {
          id: 'mn4',
          type: 'callout',
          content: '참석자: 전원 참석 | 진행: 김팀장',
        },
        {
          id: 'mn5',
          type: 'heading3',
          content: '안건',
        },
        {
          id: 'mn6',
          type: 'numbered',
          content: 'Statfordegree Hub 구축 현황 공유',
        },
        {
          id: 'mn7',
          type: 'numbered',
          content: '이번 주 업무 배분',
        },
        {
          id: 'mn8',
          type: 'numbered',
          content: '기타 공지사항',
        },
        {
          id: 'mn9',
          type: 'heading3',
          content: '결정사항',
        },
        {
          id: 'mn10',
          type: 'bullet',
          content: '허브 시스템을 팀 공식 지식관리 도구로 채택',
        },
        {
          id: 'mn11',
          type: 'bullet',
          content: '매주 월요일 회의 전날까지 업무 현황 업데이트',
        },
      ],
    },
  },
  tasks: [
    {
      id: 't1',
      title: 'Statfordegree Hub 기획 및 설계',
      description: '팀 지식관리 시스템의 요구사항 정의 및 UI/UX 설계',
      status: 'done',
      priority: 'high',
      assignee: '김개발',
      dueDate: '2025-03-01',
      tags: ['기획', '설계'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 't2',
      title: '워크스페이스 핵심 기능 개발',
      description: '페이지 편집기, 사이드바, 태스크 보드 구현',
      status: 'in_progress',
      priority: 'high',
      assignee: '이프론트',
      dueDate: '2025-03-10',
      tags: ['개발', '프론트엔드'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 't3',
      title: 'Vercel 배포 및 CI/CD 설정',
      description: 'GitHub Actions 연동 및 자동 배포 파이프라인 구축',
      status: 'in_progress',
      priority: 'medium',
      assignee: '박데브옵스',
      dueDate: '2025-03-12',
      tags: ['배포', '인프라'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 't4',
      title: '팀 매뉴얼 문서화',
      description: '온보딩 가이드, 업무 프로세스, 커뮤니케이션 규칙 작성',
      status: 'todo',
      priority: 'medium',
      assignee: '김팀장',
      dueDate: '2025-03-20',
      tags: ['문서화'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 't5',
      title: 'API 서버 설계',
      description: 'RESTful API 엔드포인트 설계 및 스웨거 문서 작성',
      status: 'todo',
      priority: 'high',
      assignee: '이프론트',
      dueDate: '2025-03-25',
      tags: ['백엔드', 'API'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 't6',
      title: '디자인 시스템 구축',
      description: '공통 컴포넌트 라이브러리 및 스타일 가이드 정의',
      status: 'todo',
      priority: 'low',
      assignee: '정디자인',
      dueDate: '2025-04-01',
      tags: ['디자인', 'UI'],
      createdAt: now,
      updatedAt: now,
    },
  ],
}
